const bebidas = [ {codigo:1, tipo:"Tequila", marca:"Silver",precio:4800},
                  {codigo:2, tipo:"Ron",marca:"Bacardi",precio: 3000 },
                  {codigo:3, tipo:"Ron",marca:"Havana",precio: 11000},
                  {codigo:4, tipo:"Whisky",marca:"Chivas",precio: 19500},
                  {codigo:5, tipo:"Whisky",marca:"Johnnie Walker",precio:70000},
                  {codigo:6, tipo:"Vodka",marca:"Sky",precio: 5000},
                  {codigo:7, tipo:"Vodka",marca:"Absolut Elyx",precio:13000},
                  {codigo:8, tipo:"Licor",marca:"Averna Amaro",precio:5000},
                  {codigo:9, tipo:"Licor",marca:"Tia Maria",precio:6000},
                  {codigo:10, tipo:"Licor", marca:"Chile Ancho Reyes",precio:13000},
                  {codigo:11, tipo:"Gin",marca:"Lario",precio:5000},
                  {codigo:12, tipo:"Grappa",marca:"Ruttini",precio:8000} ]